name: Update Citations

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-citations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    - name: Generate citations
      run: python -m scholar2bibtex.scripts.generate_citations
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update citations" && git push) 